{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPzLhiclAjwDADeI36gP8b8",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/daksh2701/ipl_analysis_project/blob/main/untitled2_py.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "IuynXjpuOhEH"
      },
      "outputs": [],
      "source": [
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "\n",
        "import streamlit as st\n",
        "import plotly.express as px\n",
        "import plotly.graph_objects as go\n",
        "\n",
        "# ------------------------------------------------\n",
        "# Page config\n",
        "# ------------------------------------------------\n",
        "st.set_page_config(\n",
        "    page_title=\"IPL Analytics Dashboard\",\n",
        "    page_icon=\"🏏\",\n",
        "    layout=\"wide\"\n",
        ")\n",
        "\n",
        "# ------------------------------------------------\n",
        "# Load data\n",
        "# ------------------------------------------------\n",
        "@st.cache_data\n",
        "def load_data():\n",
        "    matches = pd.read_csv(\"matches (2).csv\")\n",
        "    deliveries = pd.read_csv(\"deliveries.csv\")\n",
        "    return matches, deliveries\n",
        "\n",
        "matches, deliveries = load_data()\n",
        "\n",
        "# Basic preprocessing used in your notebook\n",
        "if \"date\" in matches.columns:\n",
        "    matches[\"date\"] = pd.to_datetime(matches[\"date\"])\n",
        "\n",
        "# ------------------------------------------------\n",
        "# Sidebar controls\n",
        "# ------------------------------------------------\n",
        "st.sidebar.title(\"🏏 IPL Dashboard Controls\")\n",
        "\n",
        "# Seasons list\n",
        "if \"season\" in matches.columns:\n",
        "    seasons = sorted(matches[\"season\"].dropna().unique())\n",
        "else:\n",
        "    seasons = []\n",
        "\n",
        "selected_seasons = st.sidebar.multiselect(\n",
        "    \"Select Season(s)\",\n",
        "    options=seasons,\n",
        "    default=seasons\n",
        ")\n",
        "\n",
        "# Team list\n",
        "team_cols = []\n",
        "for c in [\"team\", \"team1\", \"team2\", \"winner\", \"batting_team\", \"bowling_team\"]:\n",
        "    if c in matches.columns or c in deliveries.columns:\n",
        "        team_cols.append(c)\n",
        "\n",
        "teams_set = set()\n",
        "if \"team1\" in matches.columns:\n",
        "    teams_set |= set(matches[\"team1\"].dropna().unique())\n",
        "if \"team2\" in matches.columns:\n",
        "    teams_set |= set(matches[\"team2\"].dropna().unique())\n",
        "if \"winner\" in matches.columns:\n",
        "    teams_set |= set(matches[\"winner\"].dropna().unique())\n",
        "if \"batting_team\" in deliveries.columns:\n",
        "    teams_set |= set(deliveries[\"batting_team\"].dropna().unique())\n",
        "if \"bowling_team\" in deliveries.columns:\n",
        "    teams_set |= set(deliveries[\"bowling_team\"].dropna().unique())\n",
        "\n",
        "teams = sorted([t for t in teams_set if str(t).lower() != \"nan\"])\n",
        "\n",
        "selected_team = st.sidebar.selectbox(\n",
        "    \"Focus Team (for team-wise views)\",\n",
        "    options=[\"All\"] + teams,\n",
        "    index=0\n",
        ")\n",
        "\n",
        "st.sidebar.markdown(\"---\")\n",
        "st.sidebar.write(\"Filter applies to most charts (season-level filters).\")\n",
        "\n",
        "# Apply season filter\n",
        "if selected_seasons:\n",
        "    matches_f = matches[matches[\"season\"].isin(selected_seasons)]\n",
        "    deliveries_f = deliveries[deliveries[\"match_id\"].isin(matches_f[\"id\"])]\n",
        "else:\n",
        "    matches_f = matches.copy()\n",
        "    deliveries_f = deliveries.copy()\n",
        "\n",
        "# ------------------------------------------------\n",
        "# Title\n",
        "# ------------------------------------------------\n",
        "st.title(\"🏏 IPL Analytics Dashboard\")\n",
        "\n",
        "st.markdown(\n",
        "    \"\"\"\n",
        "This interactive dashboard is built on the IPL ball‑by‑ball and match‑level dataset used in your Jupyter notebook.\n",
        "Use the filters in the sidebar to explore seasons, teams, players, venues, and bowling/batting statistics.\n",
        "\"\"\"\n",
        ")\n",
        "\n",
        "# ------------------------------------------------\n",
        "# Tab layout\n",
        "# ------------------------------------------------\n",
        "tab1, tab2, tab3, tab4, tab5 = st.tabs([\n",
        "    \"Overview\",\n",
        "    \"Batting Analysis\",\n",
        "    \"Bowling Analysis\",\n",
        "    \"Teams & Venues\",\n",
        "    \"Season-wise Leaders\"\n",
        "])\n",
        "\n",
        "# ------------------------------------------------\n",
        "# Tab 1: Overview\n",
        "# ------------------------------------------------\n",
        "with tab1:\n",
        "    st.subheader(\"Tournament Overview\")\n",
        "\n",
        "    col1, col2, col3, col4 = st.columns(4)\n",
        "\n",
        "    # Total matches\n",
        "    total_matches = len(matches_f)\n",
        "    # Total seasons\n",
        "    total_seasons = matches_f[\"season\"].nunique() if \"season\" in matches_f.columns else 0\n",
        "    # Total teams\n",
        "    total_teams = len(teams)\n",
        "    # Total venues\n",
        "    total_venues = matches_f[\"venue\"].nunique() if \"venue\" in matches_f.columns else 0\n",
        "\n",
        "    col1.metric(\"Total Matches\", total_matches)\n",
        "    col2.metric(\"Seasons\", total_seasons)\n",
        "    col3.metric(\"Unique Teams\", total_teams)\n",
        "    col4.metric(\"Venues\", total_venues)\n",
        "\n",
        "    st.markdown(\"---\")\n",
        "\n",
        "    # Matches per season\n",
        "    if \"season\" in matches_f.columns:\n",
        "        matches_per_season = matches_f.groupby(\"season\")[\"id\"].count().reset_index()\n",
        "        matches_per_season.columns = [\"season\", \"matches\"]\n",
        "\n",
        "        fig_matches_season = px.bar(\n",
        "            matches_per_season,\n",
        "            x=\"season\",\n",
        "            y=\"matches\",\n",
        "            title=\"Matches per Season\",\n",
        "            labels={\"season\": \"Season\", \"matches\": \"Number of Matches\"},\n",
        "            text=\"matches\"\n",
        "        )\n",
        "        fig_matches_season.update_traces(textposition=\"outside\")\n",
        "        st.plotly_chart(fig_matches_season, use_container_width=True)\n",
        "\n",
        "    # Toss decision: bat vs field\n",
        "    if \"toss_decision\" in matches_f.columns:\n",
        "        toss_counts = matches_f[\"toss_decision\"].value_counts().reset_index()\n",
        "        toss_counts.columns = [\"decision\", \"count\"]\n",
        "\n",
        "        fig_toss = px.pie(\n",
        "            toss_counts,\n",
        "            names=\"decision\",\n",
        "            values=\"count\",\n",
        "            title=\"Overall Toss Decision (Bat vs Field)\",\n",
        "            hole=0.4\n",
        "        )\n",
        "        st.plotly_chart(fig_toss, use_container_width=True)\n",
        "\n",
        "    # Result type: runs vs wickets vs others\n",
        "    if \"result\" in matches_f.columns:\n",
        "        res_counts = matches_f[\"result\"].value_counts().reset_index()\n",
        "        res_counts.columns = [\"result\", \"count\"]\n",
        "\n",
        "        fig_res = px.bar(\n",
        "            res_counts,\n",
        "            x=\"result\",\n",
        "            y=\"count\",\n",
        "            title=\"Match Result Types\",\n",
        "            text=\"count\"\n",
        "        )\n",
        "        fig_res.update_traces(textposition=\"outside\")\n",
        "        st.plotly_chart(fig_res, use_container_width=True)\n",
        "\n",
        "# ------------------------------------------------\n",
        "# Tab 2: Batting Analysis\n",
        "# ------------------------------------------------\n",
        "with tab2:\n",
        "    st.subheader(\"Batting Analysis\")\n",
        "\n",
        "    # Overall top run scorers (as in notebook)\n",
        "    if {\"batter\", \"batsman_runs\"}.issubset(deliveries_f.columns):\n",
        "        top_batters = (\n",
        "            deliveries_f\n",
        "            .groupby(\"batter\")[\"batsman_runs\"]\n",
        "            .sum()\n",
        "            .reset_index()\n",
        "            .sort_values(\"batsman_runs\", ascending=False)\n",
        "        )\n",
        "        top_n = st.slider(\"Top N Run Scorers\", min_val := 5, 30, 20, step=1)\n",
        "        top_batters_n = top_batters.head(top_n)\n",
        "\n",
        "        fig_top_bat = px.bar(\n",
        "            top_batters_n,\n",
        "            x=\"batter\",\n",
        "            y=\"batsman_runs\",\n",
        "            title=f\"Top {top_n} Run Scorers (All Time)\",\n",
        "            labels={\"batter\": \"Batter\", \"batsman_runs\": \"Runs\"},\n",
        "            text=\"batsman_runs\"\n",
        "        )\n",
        "        fig_top_bat.update_layout(xaxis_tickangle=-45)\n",
        "        fig_top_bat.update_traces(textposition=\"outside\")\n",
        "        st.plotly_chart(fig_top_bat, use_container_width=True)\n",
        "\n",
        "        # Player filter for detailed view\n",
        "        selected_batter = st.selectbox(\n",
        "            \"Select Batter for Detailed Stats\",\n",
        "            options=top_batters[\"batter\"].head(50)  # limit list to top 50\n",
        "        )\n",
        "\n",
        "        player_df = deliveries_f[deliveries_f[\"batter\"] == selected_batter]\n",
        "\n",
        "        col1, col2, col3, col4 = st.columns(4)\n",
        "        total_runs = int(player_df[\"batsman_runs\"].sum())\n",
        "        total_balls = int(player_df.shape[0])\n",
        "        fours = int((player_df[\"batsman_runs\"] == 4).sum())\n",
        "        sixes = int((player_df[\"batsman_runs\"] == 6).sum())\n",
        "\n",
        "        col1.metric(\"Total Runs\", total_runs)\n",
        "        col2.metric(\"Balls Faced\", total_balls)\n",
        "        col3.metric(\"Fours\", fours)\n",
        "        col4.metric(\"Sixes\", sixes)\n",
        "\n",
        "        # Season-wise runs for selected batter\n",
        "        if \"season\" in matches_f.columns:\n",
        "            # Merge deliveries with matches for season info\n",
        "            bat_season = deliveries_f.merge(\n",
        "                matches_f[[\"id\", \"season\"]],\n",
        "                left_on=\"match_id\",\n",
        "                right_on=\"id\",\n",
        "                how=\"left\"\n",
        "            )\n",
        "            bat_season = bat_season[bat_season[\"batter\"] == selected_batter]\n",
        "            bat_season_group = (\n",
        "                bat_season.groupby(\"season\")[\"batsman_runs\"]\n",
        "                .sum()\n",
        "                .reset_index()\n",
        "                .sort_values(\"season\")\n",
        "            )\n",
        "\n",
        "            fig_bat_season = px.line(\n",
        "                bat_season_group,\n",
        "                x=\"season\",\n",
        "                y=\"batsman_runs\",\n",
        "                markers=True,\n",
        "                title=f\"Season-wise Runs – {selected_batter}\"\n",
        "            )\n",
        "            st.plotly_chart(fig_bat_season, use_container_width=True)\n",
        "\n",
        "# ------------------------------------------------\n",
        "# Tab 3: Bowling Analysis\n",
        "# ------------------------------------------------\n",
        "with tab3:\n",
        "    st.subheader(\"Bowling Analysis\")\n",
        "\n",
        "    # Overall wicket takers (your notebook uses dismissal filter)\n",
        "    if {\"bowler\", \"is_wicket\"}.issubset(deliveries_f.columns):\n",
        "        # Count only valid dismissals\n",
        "        wicket_df = deliveries_f[\n",
        "            (deliveries_f[\"is_wicket\"] == 1) &\n",
        "            (~deliveries_f[\"dismissal_kind\"].isin([\"run out\", \"retired hurt\", \"obstructing the field\"]))\n",
        "        ]\n",
        "        top_bowlers = (\n",
        "            wicket_df.groupby(\"bowler\")[\"is_wicket\"]\n",
        "            .count()\n",
        "            .reset_index()\n",
        "            .rename(columns={\"is_wicket\": \"wicket_counted\"})\n",
        "            .sort_values(\"wicket_counted\", ascending=False)\n",
        "        )\n",
        "\n",
        "        top_n_bowl = st.slider(\"Top N Wicket Takers\", 5, 30, 20, step=1)\n",
        "        top_bowlers_n = top_bowlers.head(top_n_bowl)\n",
        "\n",
        "        fig_top_bowl = px.bar(\n",
        "            top_bowlers_n,\n",
        "            x=\"bowler\",\n",
        "            y=\"wicket_counted\",\n",
        "            title=f\"Top {top_n_bowl} Wicket Takers (All Time)\",\n",
        "            labels={\"bow\n"
      ]
    }
  ]
}